- name: configure db server
  hosts: db
  become: yes
  vars:
    login_host: db.purvanshi.online
    mysql_root_password: ExpenseApp@1
  tasks:
  - name: install mysql-server
    ansible.builtin.dnf:
      name: mysql-server
      state: latest

  - name: start and enable mysql server
    ansible.builtin.service:
      name: mysqld
      state: start
      enable: yes
# check password is already setup or not
  - name: check db connections
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: "{{ login_host }}"
      filter: version
    ignoe_errors: yes
    register: mysql_connection_output

  - name: print output
  ansible.builtin.debug:
    msg: "Output: {{mysql_connection_output}}"
  